/** Re-exports blank-paint pattern APIs. */
export {
  createBlankPattern,
  type Pattern,
  type PreviewKind,
  AIDA,
  AIDA_RGB,
  PAPER,
  PAPER_PINK,
  DIM_MIN,
  DIM_MAX,
  clampDim,
  sampleImage,
  pixelsToPattern,
  imageToPattern,
  ensureFloss,
  setCell,
  paintCell,
  medianCut,
} from "./pattern_core";
export {
  type CellHit,
  hitTestCell,
  loadImageFile,
  isUnusedFloss,
  contrastInk,
  tilePad,
  drawTilePreview,
  chartGutter,
  chartCanvasSize,
  drawChartPreview,
  renderPatternToCanvas,
} from "./pattern_draw";
export {
  exampleHeart,
  exampleFlower,
  exampleBird,
  EXAMPLES,
  printChartHtml,
} from "./pattern_examples";
