import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import type { Floss } from "./palette";
import { PALETTE } from "./palette";
import {
  EXAMPLES,
  type Pattern,
  type PreviewKind,
  DIM_MAX,
  DIM_MIN,
  chartCanvasSize,
  clampDim,
  createBlankPattern,
  drawChartPreview,
  drawTilePreview,
  hitTestCell,
  imageToPattern,
  loadImageFile,
  paintCell,
  tilePad,
  fillRegion,
  pickFlossAt,
  PatternHistory,
  patternStats,
  exportPixelPng,
  downloadCanvasPng,
  exportPreviewPng,
  exportPatternPdf,
  PNG_SCALES,
} from "./pattern";

export type Lang = "es" | "en";
export type StudioTool = "highlight" | "paint" | "erase" | "fill" | "eyedropper";

export const COPY = {
  es: {
    bio: "Convierte tus fotos en mosaicos brillantes y gráficos para armar con cuentas.",
    create: "Crear patrón",
    examples: "Ver ejemplos",
    studio: "Estudio",
    upload: "Subir imagen",
    drop: "Arrastra una foto o elige un archivo",
    width: "Ancho",
    height: "Alto",
    colors: "Colores",
    exportPng: "Exportar PNG",
    print: "Imprimir",
    reset: "Reiniciar",
    legend: "Leyenda",
    empty: "Sube una imagen, crea una plantilla vacía o elige un ejemplo.",
    langToggle: "EN",
    preview: "Vista previa",
    tiles: "Azulejos",
    chart: "Gráfico",
    share: "Compartir",
    blank: "Plantilla vacía",
    paint: "Pintar",
    erase: "Borrar",
    highlight: "Resaltar",
    paintHint: "Elige un color y toca las celdas del gráfico o mosaico.",
    eraseHint: "Toca celdas para volver a tela AIDA.",
    paintPalette: "Paleta para pintar",
    cells: "celdas",
    fill: "Rellenar",
    eyedropper: "Cuentagotas",
    undo: "Deshacer",
    redo: "Rehacer",
    zoom: "Zoom",
    grid: "Cuadrícula",
    patternInfo: "Patrón",
    size: "Tamaño",
    stitches: "Puntadas",
    estimatedFloss: "Hilo estimado",
    compare: "Comparar",
    original: "Original",
    pixelArt: "Pixel art",
    exportPngPixel: "PNG píxeles",
    exportPattern: "Patrón",
    exportPdf: "PDF",
  },
  en: {
    bio: "Turn your photos into glossy tile mosaics and bead charts, ready to make.",
    create: "Create pattern",
    examples: "See examples",
    studio: "Studio",
    upload: "Upload image",
    drop: "Drop a photo or choose a file",
    width: "Width",
    height: "Height",
    colors: "Colors",
    exportPng: "Export PNG",
    print: "Print",
    reset: "Reset",
    legend: "Legend",
    empty: "Upload an image, create a blank template, or pick an example.",
    langToggle: "ES",
    preview: "Preview",
    tiles: "Tiles",
    chart: "Chart",
    share: "Share",
    blank: "Blank template",
    paint: "Paint",
    erase: "Erase",
    highlight: "Highlight",
    paintHint: "Pick a color, then tap cells on the chart or tiles.",
    eraseHint: "Tap cells to restore AIDA cloth.",
    paintPalette: "Paint palette",
    cells: "cells",
    fill: "Fill",
    eyedropper: "Eyedropper",
    undo: "Undo",
    redo: "Redo",
    zoom: "Zoom",
    grid: "Grid",
    patternInfo: "Pattern",
    size: "Size",
    stitches: "Stitches",
    estimatedFloss: "Estimated floss",
    compare: "Compare",
    original: "Original",
    pixelArt: "Pixel art",
    exportPngPixel: "PNG pixels",
    exportPattern: "Pattern",
    exportPdf: "PDF",
  },
};

export const SIZE_PRESETS = [16, 24, 32, 48, 64, 80] as const;
export const COLOR_COUNTS = [8, 16, 24, 32] as const;

/** Curated DMC-like chips for blank painting (still honest palette). */
export function flossByCode(code: string): Floss {
  const f = PALETTE.find((x) => x.code === code);
  if (!f) throw new Error(`Missing paint floss ${code}`);
  return f;
}

export const PAINT_FLOSS: Floss[] = [
  "310",
  "321",
  "666",
  "947",
  "743",
  "907",
  "825",
  "797",
  "550",
  "718",
  "B5200",
  "Ecru",
].map(flossByCode);
